"""An in-process ModelRegistry that exercises the real artifact path.

A fake that returns a URI string would leave the entire ingest path -- stream,
hash, unpack, cache -- untested until the first live CAI session. So this one
synthesizes genuine gzipped MLflow-layout tarballs.

The bytes are **byte-for-byte reproducible across processes and machines**. That
is not fastidiousness: the artifact cache is keyed by content lineage and the
device verifies a SHA-256, so a fake whose digest changed per run would make
every cache and checksum test intermittently fail, and intermittent checksum
failures are genuinely horrible to debug. Determinism needs three things, all of
which are easy to lose by accident:

  * `gzip.GzipFile(mtime=0)` -- the gzip header embeds a timestamp by default;
  * every TarInfo's mtime/uid/gid/uname/gname/mode pinned;
  * members added in a fixed order with a deterministic payload generator.

The `model.onnx` member is a **real, loadable ONNX graph**, padded with
pseudo-random bytes up to the requested size. It used to be only the padding --
chained SHA-256, which `onnxruntime` rejects with `INVALID_PROTOBUF` -- and that
was fine while the only consumer was a mock runtime checking presence, size and
digest. It stopped being fine in M4, when a real `InferenceSession` became the
consumer: a fixture that cannot load makes the entire ONNX path untestable off
the device. See `_padded_onnx` for how both properties are kept at once.
"""

from __future__ import annotations

import base64
import gzip
import hashlib
import io
import tarfile
from datetime import datetime, timedelta, timezone

from lighthouse_contracts import ArtifactFormat, Packaging

from .base import (
    ArtifactStream,
    ModelNotFound,
    ModelRegistry,
    RegistryModelVersion,
    RegistryUnavailable,
    UnsupportedFlavor,
    VersionNotReady,
)

# Fixed epoch for all tar member timestamps. Any constant works; it just must not
# be "now".
_FIXED_MTIME = 0

# Base instant for synthetic created_at values, so model listings are stable too.
_EPOCH = datetime(2026, 1, 1, tzinfo=timezone.utc)


def _deterministic_payload(seed: str, size: int) -> bytes:
    """Reproducible pseudo-random bytes.

    Chained SHA-256 over a counter: no RNG state, no seeding API differences
    between Python versions, identical output everywhere.
    """
    out = bytearray()
    counter = 0
    seed_bytes = seed.encode("utf-8")
    while len(out) < size:
        out += hashlib.sha256(seed_bytes + counter.to_bytes(8, "big")).digest()
        counter += 1
    return bytes(out[:size])


# Generated by `python scripts/build_model.py --emit-fixture`. Do not hand-edit:
# `--self-check` compares this constant against the builder's output and fails
# if they have drifted. 1214 bytes, sha256 120929b9085925d9...
FASHION_ONNX_BASE64 = (
    "CAkSFmxpZ2h0aG91c2UtYnVpbGQtbW9kZWwaATE6mAkKiwEKBWlucHV0CgZjb252X3cKBmNvbnZf"
    "YhIIY29udl9vdXQaBGNvbnYiBENvbnYqEgoJZGlsYXRpb25zQAFAAaABByoMCgVncm91cBgBoAEC"
    "KhUKDGtlcm5lbF9zaGFwZUADQAOgAQcqEQoEcGFkc0ABQAFAAUABoAEHKhAKB3N0cmlkZXNAAUAB"
    "oAEHCiAKCGNvbnZfb3V0EghyZWx1X291dBoEcmVsdSIEUmVsdQorCghyZWx1X291dBIGcG9vbGVk"
    "GgRwb29sIhFHbG9iYWxBdmVyYWdlUG9vbAoxCgZwb29sZWQSCGZlYXR1cmVzGgdmbGF0dGVuIgdG"
    "bGF0dGVuKgsKBGF4aXMYAaABAgooCghmZWF0dXJlcwoEZmNfdxIGbG9naXRzGgZtYXRtdWwiBk1h"
    "dE11bAogCgZsb2dpdHMKBGZjX2ISBm91dHB1dBoDYWRkIgNBZGQSC2Zhc2hpb25fY25uKrUCCAgI"
    "AQgDCAMQASKgAjApvjyTASA9U1ipOmeZRb2Ss7C83/lFPa6aZzxQUEq9Kq0/PCZw6zxJgJo7mpQC"
    "vJMa2jhAFqI85gIXvbwfN7wsR0i6UdzxvF3+Q7327o+8Ko0YvZJZvTx07CA9uMs+vZENpLwRjhm9"
    "uW1fPGNfsjy6abM8gEcUPWh6Cbw01RM97j8yPb2sibzImDs8D35iOriTCDwYz6A8F0UPPVRvjTzK"
    "GnU6MH+Fu3rkD71wKDw96e8lumgIR7xDGwC9u0YLvQYsOTxMa9O6dosAPamgorxfevu87iUNPC8Z"
    "x7sPDva7ajS5uycW+Dvs2l48IbFdPIdrNbzEeiO8ie3uPMgnJD0RbUc8CTPtvAE1NTskYV88xRou"
    "PT2Z/7w0u248V+0aO0IGY29udl93Ki4ICBABIiBCmQY9LssXvSCWTbu9baY8OPWBux+/N7w1f8y8"
    "46Wbu0IGY29udl9iKs8CCAgIChABIsACfT81ves1PT2Lhzc90GKpPLd7Ob1Kszk98IvLvM/5KT0b"
    "Ejc93785PYLK+Dxgkko7gZYuPUYJOr3W5ZS5kSt1vLn8BzuHazW9BHIJPPLqHL3LZSM8iujXuw/V"
    "FL3luNO8g4gUvcIYEbzRVxC8nl8UOohp3zugG5o7sACmO9fA1jxGIrQ8Vb/SvMIUZTxpjiw8ETVR"
    "PN+pAL3L2qa7aasSu24YBT3iWm28SUr6vP4PMD2L/7u8ZM3IOcIWO72mft47jZxFvRnlGTzzj748"
    "UkVxvHjPgbyefPq8ylFAPUkrPj2fzD89BU+hPBrBRj0mGqS8IuCQvIs2Bz1Gz6088IUJPV1txTzp"
    "f7m77ZoQPEEtBr1h38487sxEPXnrPD0+y3O7++oqOj4JLD1DkIO8D3/NvI0KnDywcug8OsrBPMOa"
    "Cr1CBGZjX3cqNggBCAoQASIo48XCuhd+MD042Ju72ubGO0W4STxVphi8s2ENPfiqFb3dmJ67qpz2"
    "vEIEZmNfYlogCgVpbnB1dBIXChUIARIRCgMSAU4KAggBCgIIHAoCCBxiGQoGb3V0cHV0Eg8KDQgB"
    "EgkKAxIBTgoCCApCBAoAEA0="
)

_FASHION_ONNX = base64.b64decode(FASHION_ONNX_BASE64)

# Protobuf field 536870911 (2**29 - 1, the largest legal field number), wire
# type 2. Appending `tag || varint(n) || n bytes` to a serialized model is how
# the fixture stays both loadable *and* an arbitrary size.
#
# Why an unknown field and not something more obvious:
#
#   * A parser must skip an unrecognised length-delimited field by its length
#     prefix -- that is how protobuf forward compatibility works at all, in
#     every implementation ever shipped. So the padding is invisible to
#     `onnx.load`, and measured: onnx 1.23.1 parses it, `check_model(
#     full_check=True)` accepts it, re-serializing returns the *same bytes*,
#     and onnxruntime 1.30.0 loads and runs the result.
#   * 536870912 raises `DecodeError`, which is the useful half of that
#     measurement: the parser really does validate field numbers, so 536870911
#     is a genuine boundary rather than a number that happened to work.
#   * `doc_string` (field 6) also worked, but did not round-trip
#     byte-identically and leans on proto2 string fields tolerating non-UTF-8 --
#     a bet against whatever older protobuf NVIDIA's aarch64 onnxruntime links.
#     Not a bet worth taking for bytes that exist to be padding.
_PAD_FIELD_TAG = b"\xfa\xff\xff\xff\x0f"


def _varint(value: int) -> bytes:
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if not value:
            out.append(byte)
            return bytes(out)
        out.append(byte | 0x80)


def _padded_onnx(seed: str, target_size: int) -> bytes:
    """The real graph, grown to roughly `target_size` bytes.

    Two things have to be true of this member at the same time, and they pull in
    opposite directions. It must *load* -- a real `InferenceSession` is the
    consumer now. And it must be arbitrarily large, because the download tests
    are about chunking, resume and `Range` arithmetic, and a 1 KB artifact
    exercises none of that (`test_end_to_end` asks for 3 MiB to get three
    chunks).

    Padding resolves it. The graph is never regenerated at a different size --
    there is one fixture graph, byte-identical everywhere -- and the extra bytes
    ride along in a field no ONNX reader looks at.

    `target_size` is a **target, not an exact size**, in two directions. It can
    be missed high by a byte, because the length prefix has to describe itself
    and varint length is a step function. And it is missed low for any target
    the padding cannot reach -- the graph itself, plus the six bytes of the
    smallest possible padding field -- where the member is just the bare graph.
    Measured: 4096, 65536 and 3 MiB all land exactly, which is every size the
    suite actually asks for.
    """
    budget = target_size - len(_FASHION_ONNX) - len(_PAD_FIELD_TAG)
    if budget < 2:
        # Not even room for a 1-byte field. The member is the bare graph, which
        # is still a valid artifact -- just smaller than the caller asked for.
        return _FASHION_ONNX
    # Solve `n + len(varint(n)) >= budget` for the smallest n. Starting below the
    # answer and stepping up, because varint length is a step function of n and
    # there are budgets with no exact solution -- overshooting by one byte is
    # correct under floor semantics, undershooting is not.
    n = budget - len(_varint(budget))
    while n + len(_varint(n)) < budget:
        n += 1
    return _FASHION_ONNX + _PAD_FIELD_TAG + _varint(n) + _deterministic_payload(seed, n)


def _mlmodel_yaml(model_name: str, version: str, onnx_path: str) -> str:
    """An MLflow `MLmodel` descriptor with an onnx flavor.

    Mirrors what `mlflow.onnx.log_model()` writes, because the artifact service
    reads `flavors.onnx.data` out of this to learn the entrypoint. If the shape
    here drifted from reality, M2 would be the first thing to notice.
    """
    return (
        "artifact_path: model\n"
        "flavors:\n"
        "  onnx:\n"
        f"    data: {onnx_path}\n"
        "    onnx_version: 1.15.0\n"
        "    providers:\n"
        "    - CUDAExecutionProvider\n"
        "    - CPUExecutionProvider\n"
        "  python_function:\n"
        "    env: conda.yaml\n"
        "    loader_module: mlflow.onnx\n"
        f"model_uuid: {hashlib.sha256(f'{model_name}:{version}'.encode()).hexdigest()[:32]}\n"
        "mlflow_version: 2.14.1\n"
        f"utc_time_created: '2026-01-01 00:00:00.000000'\n"
        "signature:\n"
        '  inputs: ''[{"name": "input", "type": "tensor", "tensor-spec": {"dtype":'
        ' "float32", "shape": [-1, 1, 28, 28]}}]''\n'
        '  outputs: ''[{"name": "output", "type": "tensor", "tensor-spec": {"dtype":'
        ' "float32", "shape": [-1, 10]}}]''\n'
    )


def build_fake_artifact(
    model_name: str,
    version: str,
    payload_size: int = 64 * 1024,
    onnx_path: str = "model.onnx",
) -> bytes:
    """Build a deterministic `model.tar.gz` in MLflow layout.

    Exposed as a module-level function so tests can assert the digest is stable
    without standing up a registry.

    `payload_size` is the **minimum** size of the `model.onnx` member, not its
    exact size: the member is a real ONNX graph plus padding, so it cannot go
    below the graph and lands within a byte above the request. Nothing depends
    on the exact value -- the two call sites passing 1024 assert on entrypoint
    resolution, and every digest in the suite is computed by calling this
    function rather than written down.
    """
    raw = io.BytesIO()
    # mtime=0 so the gzip header carries no wall-clock timestamp.
    with gzip.GzipFile(fileobj=raw, mode="wb", mtime=_FIXED_MTIME) as gz:
        # "w" (not "w:gz") -- gzip is already handled by the wrapper above, and
        # letting tarfile compress too would reintroduce its own mtime.
        with tarfile.open(fileobj=gz, mode="w", format=tarfile.PAX_FORMAT) as tar:
            members: list[tuple[str, bytes]] = [
                ("MLmodel", _mlmodel_yaml(model_name, version, onnx_path).encode("utf-8")),
                (onnx_path, _padded_onnx(f"{model_name}:{version}", payload_size)),
                (
                    "conda.yaml",
                    b"channels:\n- conda-forge\ndependencies:\n- python=3.11\n"
                    b"- pip\n- pip:\n  - onnx==1.15.0\n  - onnxruntime==1.17.0\n",
                ),
            ]
            for member_name, data in sorted(members):
                info = tarfile.TarInfo(name=member_name)
                info.size = len(data)
                info.mtime = _FIXED_MTIME
                info.mode = 0o644
                info.uid = 0
                info.gid = 0
                info.uname = ""
                info.gname = ""
                tar.addfile(info, io.BytesIO(data))
    return raw.getvalue()


class FakeModelRegistry(ModelRegistry):
    """Local stand-in for the CAI registry, with fault injection.

    Fault injection covers the registry-side failures the spec's test matrix
    needs (SS22) without mocking a network. Note that artifact *corruption* is
    injected in the serving layer, not here: the control plane hashes whatever it
    reads, so a registry cannot make it compute a wrong digest -- only the bytes
    served to the device afterwards can disagree with it.
    """

    def __init__(
        self,
        models: dict[str, list[str]] | None = None,
        *,
        payload_size: int = 64 * 1024,
        unavailable: bool = False,
        not_ready: set[tuple[str, str]] | None = None,
        no_onnx_flavor: set[tuple[str, str]] | None = None,
    ) -> None:
        self._models: dict[str, list[str]] = models or {
            "fashion-cnn": ["1", "2", "3"],
            "fraud-detector": ["6", "7"],
        }
        self._payload_size = payload_size
        self.unavailable = unavailable
        self.not_ready = not_ready or set()
        self.no_onnx_flavor = no_onnx_flavor or set()

    @property
    def name(self) -> str:
        return "fake"

    # -- fault injection -------------------------------------------------

    def _guard(self) -> None:
        if self.unavailable:
            raise RegistryUnavailable("fake registry marked unavailable")

    def set_unavailable(self, value: bool) -> None:
        """Flip reachability at runtime, for the dev harness."""
        self.unavailable = value

    def add_version(self, model_name: str, version: str) -> None:
        """Register a new version, so the dashboard can show one appearing."""
        self._models.setdefault(model_name, []).append(version)

    # -- ModelRegistry ---------------------------------------------------

    def list_models(self) -> list[str]:
        self._guard()
        return sorted(self._models)

    def list_versions(self, model_name: str) -> list[RegistryModelVersion]:
        self._guard()
        if model_name not in self._models:
            raise ModelNotFound(f"no such model: {model_name}")
        return [self._build(model_name, v) for v in self._models[model_name]]

    def get_version(self, model_name: str, version: str) -> RegistryModelVersion:
        self._guard()
        if model_name not in self._models:
            raise ModelNotFound(f"no such model: {model_name}")
        if version not in self._models[model_name]:
            raise ModelNotFound(f"no version {version} of {model_name}")
        if (model_name, version) in self.not_ready:
            raise VersionNotReady(f"{model_name} v{version} is still building")
        if (model_name, version) in self.no_onnx_flavor:
            raise UnsupportedFlavor(
                f"{model_name} v{version} has no onnx flavor; the edge cannot run it"
            )
        return self._build(model_name, version)

    def open_artifact(self, mv: RegistryModelVersion) -> ArtifactStream:
        self._guard()
        data = build_fake_artifact(mv.name, mv.version, self._payload_size)
        return ArtifactStream(
            fileobj=io.BytesIO(data),
            packaging=Packaging.MLFLOW_TAR_GZ,
            size_bytes=len(data),
            source_uri=mv.artifact_uri,
        )

    def get_artifact_uri(self, mv: RegistryModelVersion) -> str:
        return mv.artifact_uri

    def ping(self) -> bool:
        return not self.unavailable

    # -- internals -------------------------------------------------------

    def _build(self, model_name: str, version: str) -> RegistryModelVersion:
        # Stable synthetic lineage ids shaped like the registry's real ones
        # (four dash-separated 4-character groups).
        model_id = _fake_id(model_name)
        version_uuid = _fake_id(f"{model_name}:{version}")
        ready = (model_name, version) not in self.not_ready
        return RegistryModelVersion(
            name=model_name,
            version=version,
            model_id=model_id,
            version_uuid=version_uuid,
            # Mirrors the live registry: a prefix, with no object name. The
            # artifact service must resolve it, so the fake keeps that honest.
            artifact_uri=f"s3a://fake-lighthouse-bucket/data/modelregistry/{model_id}/{version_uuid}",
            status="READY" if ready else "PENDING",
            format=ArtifactFormat.ONNX,
            packaging=Packaging.MLFLOW_TAR_GZ,
            created_at=_EPOCH + timedelta(days=int(version) if version.isdigit() else 0),
            entrypoint="model.onnx",
            size_bytes=None,  # unknown until read, as with the real registry
        )


def _fake_id(seed: str) -> str:
    """A stable identifier shaped like a registry id (`abcd-efgh-ijkl-mnop`)."""
    h = hashlib.sha256(seed.encode("utf-8")).hexdigest()
    return "-".join(h[i : i + 4] for i in range(0, 16, 4))
